openapi: "3.1.0"
info:
  title: "chzzk_bot API"
  description: "chzzk_bot API"
  version: "1.0.0"
servers:
- url: "http://localhost:8080"
paths:
  /:
    get:
      summary: "Webroot"
      description: "Main page of this api"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /health:
    get:
      description: "Health Check endpoint"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "OK"