name: build

#event trigger : main 브랜치에 push 이벤트 발생시 jobs가 실행된다.
on:
  push:
    branches: [ "main" ]

#권한 설정
permissions:
  contents: read

#jobs 정의
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Buildpack CLI
        uses: paketo-buildpacks/pack@v1

      - name: Set datetime variable
        id: vars
        run: echo "DATETIME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and Push Native Image
        run: |
          pack build --builder paketo-buildpacks/builder:tiny . \
            --push true \
            --tag dalbodeule/chzzkbot:latest \
            --tag dalbodeule/chzzkbot:${{ env.DATETIME }}
            --platforms linux/amd64,linux/arm64