name: build

#event trigger : main 브랜치에 push 이벤트 발생시 jobs가 실행된다.
on:
  push:
    branches: [ "main" ]

#권한 설정
permissions:
  contents: read

#jobs 정의
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            dalbodeule/chzzkbot:latest
            dalbodeule/chzzkbot:$(git rev-parse --short HEAD)
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7