name: build

# event trigger: main 브랜치에 push 이벤트 발생 시 jobs가 실행된다.
on:
  push:
    branches: [ "main" ]

# 권한 설정
permissions:
  contents: read

# jobs 정의
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Buildpack CLI
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.24.0/pack-v0.24.0-linux.tgz" | tar -xzv -C /usr/local/bin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set datetime variable
        id: vars
        run: echo "DATETIME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Native Image (multi-platform)
        run: |
          pack build --builder paketobuildpacks/builder-jammy-full:latest \
            --tag dalbodeule/chzzkbot:latest \
            --tag dalbodeule/chzzkbot:${{ env.DATETIME }} \
            --publish